---

stages:
  - bootstrap
  - triggers
  - build
  - qa
  - signing
  - deploy
  - docker

before_script:
  - mkdir -p ~/.aws
  - echo "[default]" > ~/.aws/config
  # Fix nix errors about dirty tree
  - git switch $CI_COMMIT_REF_NAME
  - git reset --hard $CI_COMMIT_SHA

ci generation:
  stage: bootstrap
  tags:
    - nix
  script:
    - nix -L build .#ci.x86_64-linux
  artifacts:
    paths:
      - result/*

all ci:
  stage: triggers
  trigger:
    include:
      - job: ci generation

# Lint

check:
  stage: qa
  needs: []
  tags:
    - nix
  script:
    - nix flake show
    # - nix flake check

fmt:
  stage: qa
  needs: []
  tags:
    - nix
  script:
    - nix profile install 'nixpkgs#nixpkgs-fmt' 'nixpkgs#findutils'
    - nixpkgs-fmt --check $(find -name \*.nix)
  after_script:
    - nixpkgs-fmt $(find -name \*.nix)
    - git diff | tee nixpkgs-fmt.diff
  artifacts:
    when: on_failure
    expose_as: "nixpkgs-fmt diff"
    paths:
      - nixpkgs-fmt.diff


# Signing

nix store signing:
  stage: signing
  tags:
    - nix
  script:
    - nix store sign --recursive --key-file "${NIX_CACHE_PRIV_KEY_FILE}" --all

# Cache upload

nix cache upload:
  stage: deploy
  tags:
    - nix
  script:
    - cat "${AWS_NIX_CACHE_CREDENTIALS_FILE}" > ~/.aws/credentials
    - nix copy --to "s3://${AWS_NIX_CACHE_BUCKET}?scheme=https&endpoint=${AWS_NIX_CACHE_ENDPOINT}" --all
