---

include:
  # Overriden in .rules-default but left here for reference
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - local: .gitlab/ci/templates.yml

generate:
  extends: .generate
  script:
    - .gitlab/ci/generate-generators.sh | tee pipeline.yml
  artifacts:
    paths:
      - diffs
      - pipeline.yml

generate for forks:
  extends:
    - generate
    - .fork-default

trigger:
  extends: .trigger

trigger for forks:
  extends:
    - trigger
    - .rules-fork-default
  needs:
    - generate for forks
  trigger:
    include:
      - job: generate for forks
        artifact: pipeline.yml

# Lint

show:
  extends: .qa
  script:
    - nix flake show

show for forks:
  extends:
    - show
    - .fork-default

fmt:
  extends: .qa
  script:
    - nix run .#nixpkgs-fmt -- --check $(find -name \*.nix)
  after_script:
    - nix run .#nixpkgs-fmt -- $(find -name \*.nix)
    - git diff | tee nixpkgs-fmt.diff
  artifacts:
    when: on_failure
    expose_as: "nixpkgs-fmt diff"
    paths:
      - nixpkgs-fmt.diff

fmt for forks:
  extends:
    - fmt
    - .fork-default

# Docker

nix-docker:
  extends: .docker
  needs: []
  variables:
    IMAGE: nix
