default:
  image: nixpkgs/nix-flakes

stages:
  - build
  - qa
  - deploy

before_script:
  - mkdir -p /etc/nix
  - cat "${NIX_CONF}" > /etc/nix/nix.conf
  - mkdir -p ~/.aws
  - echo "[default]" > ~/.aws/config


# Jobs templates

.build-image-job: &build-image-job
  stage: build
  needs: []
  script:
    - cat "${AWS_NIX_CACHE_CREDENTIALS_FILE}" > ~/.aws/credentials
    - export buildExpression=".#nixosConfigurations.${IMAGE_NAME}.config.system.build.toplevel"
    - nix -L build "$buildExpression"
    - nix store sign --recursive --key-file "${NIX_CACHE_PRIV_KEY_FILE}" --all
    - nix copy --to "s3://${AWS_NIX_CACHE_BUCKET}?scheme=https&endpoint=${AWS_NIX_CACHE_ENDPOINT}" --all

.deploy-image-job: &deploy-image-job
  stage: deploy
  needs:
    - qa
  script:
    - cat "${AWS_PXE_IMAGES_CREDENTIALS_FILE}" > ~/.aws/credentials
    - export buildExpression=".#nixosConfigurations.${IMAGE_NAME}.config.system.build.toplevel-netboot"
    - nix -L build "$buildExpression"
    - nix profile install 'nixpkgs#awscli'
    - aws s3 --endpoint-url "${AWS_PXE_IMAGES_ENDPOINT}" cp --acl public-read --recursive "$(readlink -f ./result)" "s3://${AWS_PXE_IMAGES_BUCKET}"
  when: manual


# Lint

check:
  stage: qa
  needs: []
  script:
    - nix flake show
    - nix flake check

fmt:
  stage: qa
  needs: []
  script:
    - nix profile install 'nixpkgs#nixpkgs-fmt' 'nixpkgs#findutils'
    - nixpkgs-fmt --check $(find -name \*.nix)
  after_script:
    - nixpkgs-fmt $(find -name \*.nix)
    - git diff | tee nixpkgs-fmt.diff
  artifacts:
    when: on_failure
    expose_as: "nixpkgs-fmt diff"
    paths:
      - nixpkgs-fmt.diff


# Builds

nixos-exec-build:
  <<: *build-image-job
  variables:
    IMAGE_NAME: nixos-exec

nixos-pie-build:
  <<: *build-image-job
  variables:
    IMAGE_NAME: nixos-pie

nixos-sup-build:
  <<: *build-image-job
  variables:
    IMAGE_NAME: nixos-sup

nixos-spe-build:
  <<: *build-image-job
  variables:
    IMAGE_NAME: nixos-spe

nixos-test-build:
  <<: *build-image-job
  variables:
    IMAGE_NAME: nixos-test

exam-pie-build:
  <<: *build-image-job
  variables:
    IMAGE_NAME: exam-pie


# Deploys

nixos-exec-deploy:
  <<: *deploy-image-job
  needs:
    - nixos-exec-build
  variables:
    IMAGE_NAME: nixos-exec

nixos-pie-deploy:
  <<: *deploy-image-job
  needs:
    - nixos-pie-build
  variables:
    IMAGE_NAME: nixos-pie

nixos-sup-deploy:
  <<: *deploy-image-job
  needs:
    - nixos-sup-build
  variables:
    IMAGE_NAME: nixos-sup

nixos-spe-deploy:
  <<: *deploy-image-job
  needs:
    - nixos-spe-build
  variables:
    IMAGE_NAME: nixos-spe

nixos-test-deploy:
  <<: *deploy-image-job
  needs:
    - nixos-test-build
  variables:
    IMAGE_NAME: nixos-test

exam-pie-deploy:
  <<: *deploy-image-job
  needs:
    - nixos-test-build
  variables:
    IMAGE_NAME: exam-pie
