#!/usr/bin/env bash

usage() {
  echo "Usage: ${0} NAME NS1 NS2"
}

if [[ "${EUID}" -ne 0 ]]; then
  echo "This command need to be run as root."
  exit 1
fi

if [[ "${#}" -ne 3 ]]; then
  usage
  exit 1
fi

IFN="${1}"
NS1="${2}"
NS2="${3}"

ip link del "${IFN}-1-${NS1}" 2> /dev/null
ip link del "${IFN}-2-${NS2}" 2> /dev/null
