#!/usr/bin/env bash

usage() {
  echo "Usage: ${0} NAME NS"
}

if [[ "${EUID}" -ne 0 ]]; then
  echo "This command need to be run as root."
  exit 1
fi

if [[ "${#}" -ne 2 ]]; then
  usage
  exit 1
fi

IFN="${1}"
NS="${2}"

ip netns exec "${NS}" ip link del "${IFN}-1-${NS}" 2> /dev/null
