{
  imports = [
    ./afit.nix
    ./asm.nix
    ./coq.nix
    ./core.nix
    ./cpp.nix
    ./csharp.nix
    ./desktop.nix
    ./dev.nix
    ./devFunctional.nix
    ./docker.nix
    ./docker-vm.nix
    ./fuse.nix
    ./games.nix
    ./gpgpu.nix
    ./gtk.nix
    ./info9.nix
    ./java.nix
    ./js.nix
    ./latex-exam.nix
    ./libvirt.nix
    ./lisp.nix
    ./net.nix
    ./ocaml.nix
    ./opengl.nix
    ./podman.nix
    ./prolog.nix
    ./prpa.nix
    ./r.nix
    ./rust.nix
    ./scala.nix
    ./sdl.nix
    ./spider.nix
    ./sql.nix
    ./thl.nix
    ./tiger.nix
  ];
}
