---

stages:
  - generate
  - trigger
  - test
  - build
  - qa
  - deploy
  - docker
  - misc

.rules-default:
  rules:
    - if: '$CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_SOURCE_PROJECT_URL == "https://gitlab.cri.epita.fr/cri/infrastructure/nixpie"'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


.default:
  extends: .rules-default
  image: registry.cri.epita.fr/cri/infrastructure/nixpie/nix # only used for forks
  needs: []
  tags:
    - nix
  before_script:
    - mkdir -p ~/.aws
    - echo "[default]" > ~/.aws/config
    - source .gitlab/ci/utils.sh
    # Fix nix errors about dirty tree
    - git switch -t origin/master
    - git reset --hard $CI_COMMIT_SHA

.rules-fork-default:
  rules:
    - if: '$CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_SOURCE_PROJECT_URL != "https://gitlab.cri.epita.fr/cri/infrastructure/nixpie"'

.fork-default:
  extends: .rules-fork-default
  tags: []

.generate:
  extends: .default
  stage: generate
  artifacts:
    paths:
      - pipeline.yml

.generate-pipelines:
  extends: .generate
  artifacts:
    paths:
      - pipeline.yml

.trigger:
  extends: .rules-default
  stage: trigger
  trigger:
    strategy: depend
    include:
      - job: generate
        artifact: pipeline.yml

.test:
  extends: .default
  stage: test

.build:
  extends: .default
  stage: build

.qa:
  extends: .default
  stage: qa

.deploy:
  extends: .default
  stage: deploy
  needs:
    - build
  allow_failure: true
  rules:
    - when: manual

.misc:
  extends: .default
  stage: misc

.docker:
  extends: .default
  stage: docker
  needs:
    - build
  before_script:
    - !reference [.default, before_script]
    - nix_run skopeo login registry.cri.epita.fr --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
  script:
    - export buildExpression=".#${IMAGE}-docker"
    - nix -L build --impure "$buildExpression"
    - nix_run skopeo --insecure-policy copy "docker-archive:$(readlink -f ./result)" docker://$CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_SHA
    - nix_run skopeo --insecure-policy copy "docker-archive:$(readlink -f ./result)" docker://$CI_REGISTRY_IMAGE/$IMAGE:latest
  allow_failure: true
  rules:
    - when: manual

.secureboot-certs:
  variables:
    VAULT_SERVER_URL: "https://vault.cri.epita.fr"
    VAULT_AUTH_PATH: "gitlab"
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://vault.cri.epita.fr
  secrets:
    SECUREBOOT_MISC_CERT:
      vault:
        path: projects/forge/infrastructure/nixpie/certs/secureboot/misc
        field: fullchain
        engine:
          name: kv-v2
          path: gitlab
    SECUREBOOT_MISC_KEY:
      vault:
        path: projects/forge/infrastructure/nixpie/certs/secureboot/misc
        field: key
        engine:
          name: kv-v2
          path: gitlab
    SECUREBOOT_REGULAR_CERT:
      vault:
        path: projects/forge/infrastructure/nixpie/certs/secureboot/regular
        field: fullchain
        engine:
          name: kv-v2
          path: gitlab
    SECUREBOOT_REGULAR_KEY:
      vault:
        path: projects/forge/infrastructure/nixpie/certs/secureboot/regular
        field: key
        engine:
          name: kv-v2
          path: gitlab
    SECUREBOOT_EXAM_CERT:
      vault:
        path: projects/forge/infrastructure/nixpie/certs/secureboot/exam
        field: fullchain
        engine:
          name: kv-v2
          path: gitlab
    SECUREBOOT_EXAM_KEY:
      vault:
        path: projects/forge/infrastructure/nixpie/certs/secureboot/exam
        field: key
        engine:
          name: kv-v2
          path: gitlab
  before_script:
    - cp "$SECUREBOOT_MISC_CERT" certs/secureboot/misc.crt
    - cp "$SECUREBOOT_MISC_KEY" certs/secureboot/misc.key
    - cp "$SECUREBOOT_REGULAR_CERT" certs/secureboot/regular.crt
    - cp "$SECUREBOOT_REGULAR_KEY" certs/secureboot/regular.key
    - cp "$SECUREBOOT_EXAM_CERT" certs/secureboot/exam.crt
    - cp "$SECUREBOOT_EXAM_KEY" certs/secureboot/exam.key
